### ISSUE TITLE
[FR] Project Examples for PlatformIO Registry

### ISSUE THREAD

**Issue by tobbad** [stm32duino/S2-LP#13]
Hi,

Currently, the [library page](https://registry.platformio.org/libraries/stm32duino/STM32duino S2-LP) in the PlatformIO Registry doesn't contain any quick start projects for developers. Such examples serve both to highlight widespread use cases and to help newcomers to get up and running much more quickly.

Please consider adding a few comprehensive project examples to the PlatformIO Registry.

Useful links:
- https://registry.platformio.org/libraries/stm32duino/STM32duino S2-LP
- https://docs.platformio.org/en/latest/manifests/library-json/fields/examples.html

**Comment by cparata** [comment]
Hello @tobbad ,
you can find the examples of usage of the S2-LP library at these links:

https://github.com/stm32duino/X-NUCLEO-S2868A1
https://github.com/stm32duino/X-NUCLEO-S2868A2
https://github.com/stm32duino/X-NUCLEO-S2915A1

All these libraries require the S2-LP library together with the [M95640-R](https://github.com/stm32duino/M95640-R) library.
We preferred to have the examples in these libraries instead of directly in the S2-LP library because on these expansion boards we have also the dependency with the M95640-R component and in my opinion in this way the code is more modular. So, I prefer to keep the S2-LP library independent from the M95640-R library and this is the reason why you cannot find examples directly there.
My suggestion is to point to the examples contained in the repositories above as examples of usage of the S2-LP library.
Best Regards,
Carlo
